M48
; DRILL file {KiCad 7.0.9} date Tue 14 Nov 2023 04:22:49 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-14T16:22:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.2402
%
G90
G05
T1
X2.0Y-2.625
X2.0Y-3.375
X2.75Y-2.0
X2.75Y-4.0
X3.5Y-4.0
X4.25Y-4.0
X5.0Y-2.625
X5.0Y-3.375
T0
M30
